apiVersion: "streamzi.io/v1"
kind: Processor
metadata:
  name: log-data
spec:
  displayName: "Log Data"
  description: "Prints the data received to console"
  imageName: "streamziprocessors/cef-ops-log-data"
  inputs:
    - "input-data"
  outputs:
  settings: